export const CARS = [
  {
    id: 1,
    brand: 'Hyundai',
    model: 'Kona',
    price: 50000,
    image: './assets/hyundai-kona.jpg',
    isOnSale: false,
  },
  {
    id: 2,
    brand: 'Hyundai',
    model: 'Tucson',
    price: 45000,
    image: './assets/hyundai-tucson.jpg',
    isOnSale: true,
  },
  {
    id: 3,
    brand: 'Hyundai',
    model: 'Santa Fe',
    price: 75000,
    image: './assets/hyundai-santa-fe.jpg',
    isOnSale: true,
  },
  {
    id: 4,
    brand: 'Hyundai',
    model: 'i-30',
    price: 35000,
    image: './assets/hyundai-i30.jpg',
    isOnSale: false,
  },
  {
    id: 5,
    brand: 'BMW',
    model: 'X-5',
    price: 33500,
    image: './assets/bmw-x5.jpg',
    isOnSale: false,
  },
  {
    id: 6,
    brand: 'BMW',
    model: '3-er',
    price: 23500,
    image: './assets/bmw_3-er.jpg',
    isOnSale: true,
  },
  {
    id: 7,
    brand: 'BMW',
    model: 'Mini',
    price: 30500,
    image: './assets/bmw-mini.jpg',
    isOnSale: true,
  },
  {
    id: 8,
    brand: 'BMW',
    model: 'Granta',
    price: 45500,
    image: './assets/bmw-granta.jpg',
    isOnSale: false,
  },
  {
    id: 9,
    brand: 'VW',
    model: 'Passat',
    price: 55500,
    image: './assets/vw-passat.jpg',
    isOnSale: true,
  },
  {
    id: 10,
    brand: 'VW',
    model: 'Golf',
    price: 35500,
    image: './assets/vw-golf.jpg',
    isOnSale: true,
  },
  {
    id: 11,
    brand: 'VW',
    model: 'Tiguan',
    price: 65000,
    image: './assets/vw-tiguan.jpg',
    isOnSale: false,
  },
  {
    id: 12,
    brand: 'VW',
    model: 'Polo',
    price: 35000,
    image: './assets/vw-polo.jpg',
    isOnSale: true,
  },
];
